[project]
enable_telemetry = false

user_env = []

session_timeout = 3600
user_session_timeout = 1296000

cache = false
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[UI]
name = "Agentic RAG"
default_theme = "dark"
layout = "wide"
default_sidebar_state = "open"
cot = "full"

[meta]
generated_by = "2.5.5"